image: circleci/node:12.10.0-browsers

pipelines:
  default:
    - step:
        caches:
          - nodecustom
          - yarn
        script:
          - yarn install
          - yarn lint
          - yarn test:ci
          - TEST_DOMAIN=$TEST_DOMAIN yarn test:ci:e2e

definitions:
  caches:
    nodecustom: ./$JAVASCRIPT_DIR/node_modules
    yarn: $JAVASCRIPT_YARN_CACHE
